# Generated by Django 5.2.16 on 2026-07-30 08:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LensCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Editable business code such as HC, PG, or BRC.', max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LensRefractiveIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=3, unique=True, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('2.50'))])),
                ('display_name', models.CharField(blank=True, help_text='Optional name such as Standard, Thin, or Ultra Thin.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lens refractive index',
                'verbose_name_plural': 'Lens refractive indices',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='LensVisionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code such as SV, BF, or PROG.', max_length=30, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LensSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_powered', models.BooleanField(default=True)),
                ('require_both_eyes', models.BooleanField(default=True, help_text='Require compatible right-eye and left-eye values before showing this lens.')),
                ('selling_unit', models.CharField(choices=[('individual', 'Individual lens'), ('pair', 'Pair of lenses'), ('box', 'Box')], default='pair', max_length=20)),
                ('units_per_box', models.PositiveIntegerField(blank=True, help_text='Required only when the selling unit is Box.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coatings', models.ManyToManyField(blank=True, related_name='lens_specifications', to='lenses.lenscoating')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lens_specification', to='catalog.productoffer')),
                ('refractive_index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lens_specifications', to='lenses.lensrefractiveindex')),
                ('vision_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lens_specifications', to='lenses.lensvisiontype')),
            ],
            options={
                'ordering': ['vision_type', 'refractive_index', 'offer'],
            },
        ),
        migrations.CreateModel(
            name='LensPrescriptionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Administrative label describing this range.', max_length=150)),
                ('minimum_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maximum_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minimum_cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maximum_cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minimum_add_power', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maximum_add_power', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('axis_mode', models.CharField(choices=[('any', 'Any axis'), ('exact', 'Configured exact axes'), ('not_required', 'Axis not required')], default='any', max_length=20)),
                ('axis_tolerance_degrees', models.PositiveSmallIntegerField(default=0, help_text='Zero means an exact match. Used only with configured axes.', validators=[django.core.validators.MaxValueValidator(20)])),
                ('supports_prism', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_rules', to='lenses.lensspecification')),
            ],
            options={
                'ordering': ['lens', 'priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LensAllowedAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)])),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_axes', to='lenses.lensprescriptionrule')),
            ],
            options={
                'verbose_name': 'Allowed lens axis',
                'verbose_name_plural': 'Allowed lens axes',
                'ordering': ['axis'],
                'constraints': [models.UniqueConstraint(fields=('rule', 'axis'), name='uniq_axis_per_lens_rule')],
            },
        ),
    ]
