# Generated by Django 5.2.16 on 2026-07-30 08:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('lenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LensPriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('index', 'Refractive-index adjustment'), ('coating', 'Coating charge'), ('power', 'Prescription-power surcharge'), ('frame', 'Frame-related surcharge')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('amount_including_gst', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_abs_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('maximum_abs_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_abs_cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('maximum_abs_cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_add_power', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('maximum_add_power', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher-priority non-stackable rules take precedence.')),
                ('is_stackable', models.BooleanField(default=False, help_text='Stackable matching rules are all added to the quotation.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_rules', to='lenses.lenscoating')),
                ('frame_shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lens_price_rules', to='catalog.frameshape')),
                ('frame_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lens_price_rules', to='catalog.frametype')),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='lenses.lensspecification')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lens_price_rules', to='catalog.material')),
            ],
            options={
                'ordering': ['lens', 'rule_type', '-priority', 'name'],
            },
        ),
    ]
