# Generated by Django 5.2.16 on 2026-07-29 15:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTPChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=13)),
                ('purpose', models.CharField(choices=[('retail_login', 'Retail login'), ('wholesale_login', 'Wholesale login')], max_length=30)),
                ('code_digest', models.CharField(editable=False, max_length=64)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('provider_name', models.CharField(max_length=100)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'purpose', '-created_at'], name='otp_phone_purpose_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('attempt_count__lte', models.F('max_attempts'))), name='otp_attempts_not_above_max')],
            },
        ),
        migrations.CreateModel(
            name='PhoneOTPThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('purpose', models.CharField(choices=[('retail_login', 'Retail login'), ('wholesale_login', 'Wholesale login')], max_length=30)),
                ('window_started_at', models.DateTimeField(blank=True, null=True)),
                ('sends_in_window', models.PositiveSmallIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('phone_number', 'purpose'), name='unique_otp_throttle_phone_purpose')],
            },
        ),
    ]
