# Generated by Django 5.2.16 on 2026-07-30 09:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lenses', '0002_lenspricerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleLensListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogue_code', models.CharField(help_text='Editable code such as SV.CR or PROG.', max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('box_contents_unit', models.CharField(choices=[('individual_lens', 'Individual lenses'), ('pair', 'Pairs of lenses')], default='individual_lens', max_length=30)),
                ('units_per_box', models.PositiveIntegerField(default=1, help_text='Number of individual lenses or pairs contained in one wholesale box.', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('coming_soon', 'Coming soon'), ('active', 'Active'), ('discontinued', 'Discontinued')], db_index=True, default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('public_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Visible only to authorized staff.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lens', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_listing', to='lenses.lensspecification')),
            ],
            options={
                'verbose_name': 'Wholesale lens listing',
                'verbose_name_plural': 'Wholesale lens listings',
                'ordering': ['catalogue_code'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleLensVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, editable=False, max_length=24, null=True, unique=True)),
                ('supplier_code', models.CharField(blank=True, max_length=100)),
                ('base_box_price_including_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('boxes_in_stock', models.PositiveIntegerField(default=0)),
                ('minimum_order_boxes', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order_multiple_boxes', models.PositiveIntegerField(default=1, help_text='Orders must use this box multiple. For example, 5 permits 5, 10, 15, and so on.', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('sold_out', 'Sold out'), ('coming_soon', 'Coming soon'), ('discontinued', 'Discontinued')], db_index=True, default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('public_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Visible only to authorized staff.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coating', models.ForeignKey(blank=True, help_text='Leave empty for a plain or uncoated catalogue column.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_variants', to='lenses.lenscoating')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='wholesale_catalog.wholesalelenslisting')),
                ('prescription_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_variants', to='lenses.lensprescriptionrule')),
            ],
            options={
                'verbose_name': 'Wholesale lens variant',
                'verbose_name_plural': 'Wholesale lens variants',
                'ordering': ['listing', 'prescription_rule', 'coating'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleBulkPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_boxes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('maximum_boxes', models.PositiveIntegerField(blank=True, help_text='Leave empty for an open-ended final tier.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('box_price_including_gst', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_price_tiers', to='wholesale_catalog.wholesalelensvariant')),
            ],
            options={
                'verbose_name': 'Wholesale bulk-price tier',
                'verbose_name_plural': 'Wholesale bulk-price tiers',
                'ordering': ['variant', 'minimum_boxes'],
            },
        ),
        migrations.AddConstraint(
            model_name='wholesalelensvariant',
            constraint=models.UniqueConstraint(fields=('listing', 'prescription_rule', 'coating'), name='uniq_wholesale_lens_rule_coating', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='wholesalebulkpricetier',
            constraint=models.UniqueConstraint(fields=('variant', 'minimum_boxes'), name='uniq_wholesale_tier_minimum'),
        ),
    ]
