# Generated by Django 5.2.16 on 2026-07-30 15:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0002_prescription_customer_review_message_and_more'),
        ('wholesale', '0003_wholesaleverificationcontact'),
        ('wholesale_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('checkout_started', 'Checkout started'), ('converted', 'Converted to order'), ('abandoned', 'Abandoned')], db_index=True, default='open', max_length=30)),
                ('pricing_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wholesale_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_carts', to='wholesale.wholesaleaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye', models.CharField(choices=[('right', 'Right eye'), ('left', 'Left eye')], max_length=10)),
                ('boxes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('base_box_price_including_gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('applied_box_price_including_gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_per_box_including_gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_including_gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('bulk_price_tier_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('variant_snapshot', models.JSONField(blank=True, default=dict)),
                ('prescription_snapshot', models.JSONField(blank=True, default=dict)),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict)),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], db_index=True, default='invalid', max_length=20)),
                ('validation_code', models.CharField(blank=True, max_length=80)),
                ('validation_message', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wholesale_cart.wholesalecart')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_cart_items', to='prescriptions.prescription')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_cart_items', to='wholesale_catalog.wholesalelensvariant')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='wholesalecart',
            index=models.Index(fields=['wholesale_account', 'status'], name='wh_cart_account_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='wholesalecart',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'checkout_started'])), fields=('wholesale_account',), name='uniq_active_wholesale_cart'),
        ),
        migrations.AddIndex(
            model_name='wholesalecartitem',
            index=models.Index(fields=['cart', 'validation_status'], name='wh_cart_item_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='wholesalecartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'variant', 'prescription', 'eye'), name='uniq_wh_cart_line'),
        ),
        migrations.AddConstraint(
            model_name='wholesalecartitem',
            constraint=models.CheckConstraint(condition=models.Q(('boxes__gte', 1)), name='wh_cart_boxes_gte_1'),
        ),
    ]
