# Generated by Django 5.2.16 on 2026-07-30 07:48

import apps.prescriptions.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_file', models.FileField(help_text='Upload a clear prescription image or PDF. Written values are optional.', upload_to=apps.prescriptions.models.prescription_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf']), apps.prescriptions.models.validate_prescription_file_size])),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('under_review', 'Under review'), ('approved', 'Approved'), ('clarification_required', 'Clarification required'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=30)),
                ('customer_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Visible only to authorized staff.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('review_prescription', 'Can review and approve prescriptions')],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionEyeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye', models.CharField(choices=[('right', 'Right eye'), ('left', 'Left eye')], max_length=10)),
                ('sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('axis', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)])),
                ('add_power', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('distance_pd_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('near_pd_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('prism_diopters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('prism_base', models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down'), ('in', 'In'), ('out', 'Out')], max_length=10)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_values', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['prescription', 'eye'],
                'constraints': [models.UniqueConstraint(fields=('prescription', 'eye'), name='uniq_eye_per_prescription')],
            },
        ),
    ]
