# Generated by Django 5.2.16 on 2026-07-30 15:50

import apps.wholesale_orders.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_productstockalert_attempt_count_and_more'),
        ('prescriptions', '0002_prescription_customer_review_message_and_more'),
        ('wholesale', '0003_wholesaleverificationcontact'),
        ('wholesale_cart', '0001_initial'),
        ('wholesale_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=apps.wholesale_orders.models.generate_wholesale_order_number, editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('payment_pending', 'Payment pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='payment_pending', max_length=30)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('fulfillment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('business_snapshot', models.JSONField(blank=True, default=dict)),
                ('subtotal_including_gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivery_fee_including_gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('grand_total_including_gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_boxes', models.PositiveIntegerField(default=0)),
                ('customer_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_orders', to='wholesale_cart.wholesalecart')),
                ('wholesale_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_orders', to='wholesale.wholesaleaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('carrier_name', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=150)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment', to='wholesale_orders.wholesaleorder')),
            ],
        ),
        migrations.CreateModel(
            name='WholesaleOrderAddressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=30)),
                ('invoice_email', models.EmailField(max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=150)),
                ('district', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='wholesale_orders.wholesaleorder')),
            ],
            options={
                'verbose_name': 'Wholesale billing-address snapshot',
                'verbose_name_plural': 'Wholesale billing-address snapshots',
            },
        ),
        migrations.CreateModel(
            name='WholesaleOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye', models.CharField(choices=[('right', 'Right eye'), ('left', 'Left eye')], max_length=10)),
                ('boxes', models.PositiveIntegerField()),
                ('physical_units_reserved', models.PositiveIntegerField()),
                ('base_box_price_including_gst', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_box_price_including_gst', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_per_box_including_gst', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal_including_gst', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bulk_price_tier_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('variant_snapshot', models.JSONField(blank=True, default=dict)),
                ('prescription_snapshot', models.JSONField(blank=True, default=dict)),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wholesale_orders.wholesaleorder')),
                ('physical_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_order_items', to='catalog.productvariant')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_order_items', to='prescriptions.prescription')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_order_items', to='wholesale_catalog.wholesalelensvariant')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='WholesalePaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('razorpay', 'Razorpay'), ('bank_transfer', 'Bank transfer'), ('pay_at_store', 'Pay at store')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('amount_including_gst', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('idempotency_key', models.CharField(default=apps.wholesale_orders.models.generate_payment_idempotency_key, editable=False, max_length=100, unique=True)),
                ('provider_order_id', models.CharField(blank=True, max_length=150)),
                ('provider_payment_id', models.CharField(blank=True, max_length=150)),
                ('provider_signature', models.CharField(blank=True, max_length=255)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='wholesale_orders.wholesaleorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleStockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxes_reserved', models.PositiveIntegerField()),
                ('physical_units_reserved', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('released', 'Released'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='wholesale_orders.wholesaleorder')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservation', to='wholesale_orders.wholesaleorderitem')),
                ('physical_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_stock_reservations', to='catalog.productvariant')),
                ('wholesale_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='wholesale_catalog.wholesalelensvariant')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='wholesaleorder',
            index=models.Index(fields=['wholesale_account', 'status'], name='wh_order_account_status_idx'),
        ),
        migrations.AddIndex(
            model_name='wholesaleorder',
            index=models.Index(fields=['status', 'created_at'], name='wh_order_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='wholesaleorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['payment_pending', 'confirmed', 'processing', 'shipped'])), fields=('source_cart',), name='uniq_active_wh_order_per_cart'),
        ),
        migrations.AddConstraint(
            model_name='wholesaleorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('boxes__gte', 1)), name='wh_order_item_boxes_gte_1'),
        ),
        migrations.AddIndex(
            model_name='wholesalepaymentattempt',
            index=models.Index(fields=['status', 'created_at'], name='wh_pay_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='wholesalestockreservation',
            index=models.Index(fields=['status', 'expires_at'], name='wh_res_status_expiry_idx'),
        ),
    ]
