# Generated by Django 5.2.16 on 2026-07-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalepaymentattempt',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='wholesalepaymentattempt',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wholesalepaymentattempt',
            name='signature_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wholesalestockreservation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wholesaleorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refund_pending', 'Refund pending'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wholesaleorder',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment pending'), ('payment_failed', 'Payment failed'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='payment_pending', max_length=30),
        ),
    ]
