# Generated by Django 5.2.16 on 2026-07-30 16:40

import apps.wholesale_orders.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale_orders', '0003_wholesalepaymentwebhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=apps.wholesale_orders.models.generate_wholesale_invoice_number, editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('void', 'Void')], db_index=True, default='issued', max_length=20)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('seller_snapshot', models.JSONField(default=dict)),
                ('business_snapshot', models.JSONField(default=dict)),
                ('billing_address_snapshot', models.JSONField(default=dict)),
                ('items_snapshot', models.JSONField(default=list)),
                ('subtotal_including_gst', models.DecimalField(decimal_places=2, max_digits=14)),
                ('delivery_fee_including_gst', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grand_total_including_gst', models.DecimalField(decimal_places=2, max_digits=14)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='wholesale_orders.wholesaleorder')),
            ],
            options={
                'ordering': ['-issued_at', '-pk'],
                'indexes': [models.Index(fields=['status', 'issued_at'], name='wh_invoice_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='WholesaleOrderNotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment_confirmed', 'Payment confirmed'), ('payment_failed', 'Payment failed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='wholesale_orders.wholesaleorder')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='wh_notif_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'event_type', 'channel'), name='uniq_wh_order_notif')],
            },
        ),
    ]
