from django.urls import path

from . import views


app_name = "retail_orders"

urlpatterns = [
    path(
        "checkout/preview/",
        views.checkout_preview,
        name="checkout_preview",
    ),
    path(
        "checkout/create/",
        views.create_checkout,
        name="checkout_create",
    ),
    path(
        "payments/razorpay/confirm/",
        views.confirm_razorpay_payment,
        name="razorpay_confirm",
    ),
    path(
        "payments/razorpay/webhook/",
        views.razorpay_webhook,
        name="razorpay_webhook",
    ),
    path(
        "orders/",
        views.order_list,
        name="order_list",
    ),
    path(
        "orders/<str:order_number>/",
        views.order_detail,
        name="order_detail",
    ),
    path(
        "orders/<str:order_number>/cancel/",
        views.cancel_order,
        name="order_cancel",
    ),
    path(
        "staff/orders/",
        views.staff_order_list,
        name="staff_order_list",
    ),
    path(
        "staff/orders/<str:order_number>/",
        views.staff_order_detail,
        name="staff_order_detail",
    ),
    path(
        "staff/orders/<str:order_number>/start-processing/",
        views.staff_start_processing,
        name="staff_start_processing",
    ),
    path(
        "staff/orders/<str:order_number>/start-production/",
        views.staff_start_production,
        name="staff_start_production",
    ),
    path(
        "staff/orders/<str:order_number>/mark-packed/",
        views.staff_mark_packed,
        name="staff_mark_packed",
    ),
    path(
        "staff/orders/<str:order_number>/ready-for-pickup/",
        views.staff_mark_ready_for_pickup,
        name="staff_ready_for_pickup",
    ),
    path(
        "staff/orders/<str:order_number>/mark-shipped/",
        views.staff_mark_shipped,
        name="staff_mark_shipped",
    ),
    path(
        "staff/orders/<str:order_number>/record-store-payment/",
        views.staff_record_store_payment,
        name="staff_record_store_payment",
    ),
    path(
        "staff/orders/<str:order_number>/mark-delivered/",
        views.staff_mark_delivered,
        name="staff_mark_delivered",
    ),
    path(
        "staff/fulfillment-groups/<int:group_id>/"
        "customer-frame-received/",
        views.staff_record_customer_frame_received,
        name="staff_customer_frame_received",
    ),
]
