# Generated by Django 5.2.16 on 2026-07-29 14:31

import apps.wholesale.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(default=apps.wholesale.models.generate_wholesale_reference_id, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='unverified', max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('contact_person_name', models.CharField(blank=True, max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('invoice_email', models.EmailField(blank=True, max_length=254)),
                ('internal_notes', models.TextField(blank=True, help_text='Visible only to authorized staff.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_wholesale_accounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wholesale account',
                'verbose_name_plural': 'Wholesale accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
