# Generated by Django 5.2.16 on 2026-07-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wholesaleaccount',
            options={'ordering': ['-created_at'], 'permissions': [('review_wholesale_account', 'Can review and approve wholesale accounts')], 'verbose_name': 'Wholesale account', 'verbose_name_plural': 'Wholesale accounts'},
        ),
    ]
