# Generated by Django 5.2.16 on 2026-07-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0002_alter_wholesaleaccount_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleVerificationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Optional public label, such as Wholesale Support.', max_length=100)),
                ('phone_number', models.CharField(help_text='Indian phone number stored in +91 format.', max_length=13, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wholesale verification contact',
                'verbose_name_plural': 'Wholesale verification contacts',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
