# Generated by Django 5.2.16 on 2026-07-30 10:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_productoffer_supports_powered_lenses_and_more'),
        ('lenses', '0002_lenspricerule'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('checkout_started', 'Checkout started'), ('converted', 'Converted to order'), ('abandoned', 'Abandoned')], db_index=True, default='open', max_length=30)),
                ('currency', models.CharField(default='INR', editable=False, max_length=3)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RetailCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('standard', 'Standard retail product'), ('powered_eyewear', 'Prescription-powered eyewear'), ('customer_owned_frame', 'Customer-owned frame service')], max_length=30)),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('current_unit_price_including_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_total_including_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('is_non_refundable', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='retail_cart.retailcart')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retail_cart_items', to='catalog.productoffer')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PoweredEyewearConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens_quote_breakdown', models.JSONField(blank=True, default=list)),
                ('lens_quote_total_including_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('configured_unit_price_including_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quote_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='powered_cart_configurations', to='lenses.lensspecification')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='powered_cart_configurations', to='prescriptions.prescription')),
                ('selected_coatings', models.ManyToManyField(blank=True, related_name='powered_cart_configurations', to='lenses.lenscoating')),
                ('cart_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='powered_configuration', to='retail_cart.retailcartitem')),
            ],
            options={
                'verbose_name': 'Powered-eyewear configuration',
                'verbose_name_plural': 'Powered-eyewear configurations',
            },
        ),
        migrations.CreateModel(
            name='CustomerOwnedFrameService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_choice', models.CharField(choices=[('fit_and_return', 'Fit lenses and return complete eyewear'), ('send_lenses_only', 'Send lenses only')], max_length=30)),
                ('frame_handling', models.CharField(choices=[('not_required', 'Frame not required'), ('bring_to_store', 'Bring frame to store'), ('send_to_store', 'Send frame to store')], default='not_required', max_length=30)),
                ('customer_notes', models.TextField(blank=True)),
                ('lens_quote_breakdown', models.JSONField(blank=True, default=list)),
                ('lens_quote_total_including_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('configured_unit_price_including_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quote_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_frame_cart_services', to='lenses.lensspecification')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_frame_cart_services', to='prescriptions.prescription')),
                ('selected_coatings', models.ManyToManyField(blank=True, related_name='owned_frame_cart_services', to='lenses.lenscoating')),
                ('cart_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_frame_service', to='retail_cart.retailcartitem')),
            ],
            options={
                'verbose_name': 'Customer-owned frame service',
                'verbose_name_plural': 'Customer-owned frame services',
            },
        ),
        migrations.AddConstraint(
            model_name='retailcart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('user',), name='uniq_open_retail_cart_user'),
        ),
        migrations.AddConstraint(
            model_name='retailcartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 10)), name='retail_item_quantity_1_to_10'),
        ),
        migrations.AddConstraint(
            model_name='retailcartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'customer_owned_frame'), ('offer__isnull', True)), models.Q(('item_type__in', ['standard', 'powered_eyewear']), ('offer__isnull', False)), _connector='OR'), name='retail_item_offer_shape'),
        ),
        migrations.AddConstraint(
            model_name='retailcartitem',
            constraint=models.CheckConstraint(condition=models.Q(('item_type', 'standard'), ('quantity', 1), _connector='OR'), name='retail_custom_item_quantity_one'),
        ),
        migrations.AddConstraint(
            model_name='retailcartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('item_type', 'standard')), fields=('cart', 'offer'), name='uniq_standard_offer_per_retail_cart'),
        ),
    ]
