CATALOGUE_MANAGER = "Catalogue Manager"
INVENTORY_MANAGER = "Inventory Manager"
PRESCRIPTION_REVIEWER = "Prescription Reviewer"
ORDER_MANAGER = "Order Manager"
ACCOUNTS_MANAGER = "Accounts Manager"


STAFF_GROUP_NAMES = (
    CATALOGUE_MANAGER,
    INVENTORY_MANAGER,
    PRESCRIPTION_REVIEWER,
    ORDER_MANAGER,
    ACCOUNTS_MANAGER,
)


STAFF_GROUP_PERMISSIONS = {
    CATALOGUE_MANAGER: (
        ("catalog", "view_brand"),
        ("catalog", "add_brand"),
        ("catalog", "change_brand"),
        ("catalog", "view_category"),
        ("catalog", "add_category"),
        ("catalog", "change_category"),
        ("catalog", "view_colour"),
        ("catalog", "add_colour"),
        ("catalog", "change_colour"),
        ("catalog", "view_material"),
        ("catalog", "add_material"),
        ("catalog", "change_material"),
        ("catalog", "view_frameshape"),
        ("catalog", "add_frameshape"),
        ("catalog", "change_frameshape"),
        ("catalog", "view_frametype"),
        ("catalog", "add_frametype"),
        ("catalog", "change_frametype"),
        ("catalog", "view_productdesign"),
        ("catalog", "add_productdesign"),
        ("catalog", "change_productdesign"),
        ("catalog", "view_productvariant"),
        ("catalog", "add_productvariant"),
        ("catalog", "change_productvariant"),
        ("catalog", "view_productoffer"),
        ("catalog", "add_productoffer"),
        ("catalog", "change_productoffer"),
        ("catalog", "view_productimage"),
        ("catalog", "add_productimage"),
        ("catalog", "change_productimage"),
        ("lenses", "view_lensvisiontype"),
        ("lenses", "add_lensvisiontype"),
        ("lenses", "change_lensvisiontype"),
        ("lenses", "view_lensrefractiveindex"),
        ("lenses", "add_lensrefractiveindex"),
        ("lenses", "change_lensrefractiveindex"),
        ("lenses", "view_lenscoating"),
        ("lenses", "add_lenscoating"),
        ("lenses", "change_lenscoating"),
        ("lenses", "view_lensspecification"),
        ("lenses", "add_lensspecification"),
        ("lenses", "change_lensspecification"),
        ("lenses", "view_lensprescriptionrule"),
        ("lenses", "add_lensprescriptionrule"),
        ("lenses", "change_lensprescriptionrule"),
        ("lenses", "view_lensallowedaxis"),
        ("lenses", "add_lensallowedaxis"),
        ("lenses", "change_lensallowedaxis"),
        ("lenses", "view_lenspricerule"),
        ("lenses", "add_lenspricerule"),
        ("lenses", "change_lenspricerule"),
        ("wholesale_catalog", "view_wholesalelenslisting"),
        ("wholesale_catalog", "add_wholesalelenslisting"),
        ("wholesale_catalog", "change_wholesalelenslisting"),
        ("wholesale_catalog", "view_wholesalelensvariant"),
        ("wholesale_catalog", "add_wholesalelensvariant"),
        ("wholesale_catalog", "change_wholesalelensvariant"),
        ("wholesale_catalog", "view_wholesalebulkpricetier"),
        ("wholesale_catalog", "add_wholesalebulkpricetier"),
        ("wholesale_catalog", "change_wholesalebulkpricetier"),
        ("catalog", "view_productstockalert"),
        ("catalog", "change_productstockalert"),
    ),
    INVENTORY_MANAGER: (
        ("catalog", "view_productvariant"),
        ("catalog", "change_productvariant"),
        ("catalog", "view_productoffer"),
        ("catalog", "change_productoffer"),
        ("catalog", "view_productstockalert"),
        ("catalog", "change_productstockalert"),
        ("wholesale_catalog", "view_wholesalelenslisting"),
        ("wholesale_catalog", "view_wholesalelensvariant"),
        ("wholesale_catalog", "change_wholesalelensvariant"),
        ("wholesale_catalog", "view_wholesalebulkpricetier"),
    ),
    PRESCRIPTION_REVIEWER: (
        ("accounts", "view_user"),
        ("prescriptions", "view_prescription"),
        ("prescriptions", "change_prescription"),
        ("prescriptions", "review_prescription"),
        ("prescriptions", "view_prescriptionnotificationevent"),
        ("prescriptions", "view_prescriptioneyevalue"),
        ("prescriptions", "add_prescriptioneyevalue"),
        ("prescriptions", "change_prescriptioneyevalue"),
        ("lenses", "view_lensspecification"),
        ("lenses", "view_lensprescriptionrule"),
        ("lenses", "view_lensallowedaxis"),
    ),
    ORDER_MANAGER: (
        ("locations", "view_address"),
        ("locations", "view_serviceablepincode"),
        ("locations", "add_serviceablepincode"),
        ("locations", "change_serviceablepincode"),
        ("retail_cart", "view_retailcart"),
        ("retail_cart", "view_retailcartitem"),
        ("retail_cart", "view_poweredeyewearconfiguration"),
        ("retail_cart", "view_customerownedframeservice"),
        ("wholesale_cart", "view_wholesalecart"),
        ("wholesale_cart", "view_wholesalecartitem"),
        ("wholesale_orders", "view_wholesaleorder"),
        ("wholesale_orders", "change_wholesaleorder"),
        (
            "wholesale_orders",
            "view_wholesaleorderaddresssnapshot",
        ),
        ("wholesale_orders", "view_wholesaleorderitem"),
        (
            "wholesale_orders",
            "view_wholesalepaymentattempt",
        ),
        (
            "wholesale_orders",
            "change_wholesalepaymentattempt",
        ),
        (
            "wholesale_orders",
            "view_wholesalefulfillment",
        ),
        (
            "wholesale_orders",
            "change_wholesalefulfillment",
        ),
        (
            "wholesale_orders",
            "view_wholesalestockreservation",
        ),
        (
            "wholesale_orders",
            "change_wholesalestockreservation",
        ),
        (
            "wholesale_orders",
            "view_wholesalepaymentwebhookevent",
        ),
        (
            "wholesale_orders",
            "view_wholesaleordernotificationevent",
        ),
        (
            "wholesale_orders",
            "view_wholesaleinvoice",
        ),
        ("retail_orders", "view_storelocation"),
        ("retail_orders", "add_storelocation"),
        ("retail_orders", "change_storelocation"),
        ("retail_orders", "view_retailcheckoutpolicy"),
        ("retail_orders", "add_retailcheckoutpolicy"),
        ("retail_orders", "change_retailcheckoutpolicy"),
        ("retail_orders", "view_retailorder"),
        ("retail_orders", "change_retailorder"),
        ("retail_orders", "view_retailorderaddresssnapshot"),
        ("retail_orders", "view_retailfulfillmentgroup"),
        ("retail_orders", "change_retailfulfillmentgroup"),
        ("retail_orders", "view_retailorderitem"),
        ("retail_orders", "view_retailstockreservation"),
        ("retail_orders", "change_retailstockreservation"),
        ("retail_orders", "view_retailpaymentattempt"),
        ("retail_orders", "change_retailpaymentattempt"),
        ("retail_orders", "view_retailordernotificationevent"),
        ("retail_orders", "change_retailordernotificationevent"),
        ("retail_orders", "view_retailpaymentwebhookevent"),
        ("retail_orders", "change_retailpaymentwebhookevent"),
        ("retail_orders", "view_retailorderstatushistory"),
        ("retail_orders", "view_retailfulfillmentstatushistory"),
    ),
    ACCOUNTS_MANAGER: (
        ("accounts", "view_user"),
        ("wholesale", "view_wholesaleaccount"),
        ("wholesale", "change_wholesaleaccount"),
        ("wholesale", "review_wholesale_account"),
        ("locations", "view_address"),
        ("locations", "add_address"),
        ("locations", "change_address"),
    ),
}
