# Generated by Django 5.2.16 on 2026-07-30 07:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=130, null=True, unique=True)),
                ('code', models.CharField(help_text='Three-letter internal code, such as FRM or SUN.', max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hex_value', models.CharField(blank=True, help_text='Optional display colour such as #000000.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hexadecimal colour such as #000000.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FrameShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FrameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=280, null=True, unique=True)),
                ('supplier_model_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('kind', models.CharField(choices=[('frame', 'Frame design'), ('lens', 'Lens'), ('accessory', 'Accessory')], default='frame', max_length=20)),
                ('gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex'), ('kids', 'Kids')], default='unisex', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('coming_soon', 'Coming soon'), ('active', 'Active'), ('discontinued', 'Discontinued')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_designs', to='catalog.brand')),
                ('categories', models.ManyToManyField(blank=True, related_name='product_designs', to='catalog.category')),
                ('frame_shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_designs', to='catalog.frameshape')),
                ('frame_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_designs', to='catalog.frametype')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_designs', to='catalog.material')),
            ],
            options={
                'ordering': ['name', 'supplier_model_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(blank=True, help_text='Examples: Small, Medium, Large, Free Size.', max_length=50)),
                ('supplier_variant_code', models.CharField(blank=True, max_length=100)),
                ('physical_sku', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('lens_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('lens_height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frame_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_mode', models.CharField(choices=[('quantity', 'Track exact quantity'), ('status_only', 'Status only')], default='status_only', max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('manual_stock_status', models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold out'), ('coming_soon', 'Coming soon')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='catalog.colour')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.productdesign')),
            ],
            options={
                'ordering': ['design', 'colour', 'size_label'],
            },
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('frame_only', 'Frame only'), ('zero_power', 'Zero-power eyewear'), ('sunglasses', 'Sunglasses'), ('accessory', 'Accessory'), ('lens', 'Lens')], max_length=30)),
                ('sku', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('mrp_including_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('selling_price_including_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gst_rate', models.DecimalField(decimal_places=2, help_text='Enter the applicable GST percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('coming_soon', 'Coming soon'), ('available', 'Available'), ('sold_out', 'Sold out'), ('discontinued', 'Discontinued')], db_index=True, default='draft', max_length=20)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['variant', 'offer_type'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/products/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(blank=True, help_text='Leave empty for a general variant image. Select an offer for an offer-specific image.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productoffer')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='productdesign',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_model_number', ''), _negated=True), fields=('brand', 'supplier_model_number'), name='uniq_brand_supplier_model'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('design', 'colour', 'size_label'), name='uniq_design_colour_size'),
        ),
        migrations.AddConstraint(
            model_name='productoffer',
            constraint=models.UniqueConstraint(fields=('variant', 'offer_type'), name='uniq_variant_offer_type'),
        ),
        migrations.AddConstraint(
            model_name='productoffer',
            constraint=models.CheckConstraint(condition=models.Q(('mrp_including_gst__isnull', True), ('selling_price_including_gst__isnull', True), ('selling_price_including_gst__lte', models.F('mrp_including_gst')), _connector='OR'), name='offer_selling_price_not_above_mrp'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('offer__isnull', True)), fields=('variant',), name='uniq_primary_general_variant_image'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('offer__isnull', False)), fields=('offer',), name='uniq_primary_offer_image'),
        ),
    ]
