# Generated by Django 5.2.16 on 2026-07-30 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='supports_powered_lenses',
            field=models.BooleanField(default=False, help_text='Allow the customer to combine this eyewear offer with prescription-powered lenses.'),
        ),
        migrations.CreateModel(
            name='ProductStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('destination', models.CharField(editable=False, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('notified', 'Notified'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_alerts', to='catalog.productoffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product stock alert',
                'verbose_name_plural': 'Product stock alerts',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'offer', 'channel'), name='uniq_active_product_stock_alert')],
            },
        ),
    ]
