# Generated by Django 5.2.16 on 2026-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productoffer_supports_powered_lenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstockalert',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productstockalert',
            name='delivery_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productstockalert',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productstockalert',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('notified', 'Notified'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='active', max_length=20),
        ),
    ]
