# Generated by Django 5.2.16 on 2026-07-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorderaddresssnapshot',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
