# Generated by Django 5.2.16 on 2026-07-30 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0003_retailpaymentwebhookevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailFulfillmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_fulfillment_status_changes', to=settings.AUTH_USER_MODEL)),
                ('fulfillment_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='retail_orders.retailfulfillmentgroup')),
            ],
            options={
                'verbose_name': 'Retail fulfillment status history',
                'verbose_name_plural': 'Retail fulfillment status histories',
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['fulfillment_group', '-created_at'], name='ret_ful_hist_group_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('previous_status', models.F('new_status')), _negated=True), name='ret_ful_hist_status_diff')],
            },
        ),
        migrations.CreateModel(
            name='RetailOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('production', 'Prescription/lens production'), ('ready_for_pickup', 'Ready for pickup'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment failed')], max_length=30)),
                ('new_status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('production', 'Prescription/lens production'), ('ready_for_pickup', 'Ready for pickup'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment failed')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='retail_orders.retailorder')),
            ],
            options={
                'verbose_name': 'Retail order status history',
                'verbose_name_plural': 'Retail order status histories',
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='ret_ord_hist_order_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('previous_status', models.F('new_status')), _negated=True), name='ret_ord_hist_status_diff')],
            },
        ),
    ]
